// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Order struct {
	ID          int32          `json:"id"`
	UserID      sql.NullInt32  `json:"user_id"`
	SareeID     sql.NullInt32  `json:"saree_id"`
	Quantity    sql.NullInt32  `json:"quantity"`
	TotalAmount string         `json:"total_amount"`
	Status      sql.NullString `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type Payment struct {
	ID                int32          `json:"id"`
	OrderID           sql.NullInt32  `json:"order_id"`
	RazorpayOrderID   string         `json:"razorpay_order_id"`
	RazorpayPaymentID string         `json:"razorpay_payment_id"`
	RazorpaySignature string         `json:"razorpay_signature"`
	Amount            string         `json:"amount"`
	Currency          sql.NullString `json:"currency"`
	Status            sql.NullString `json:"status"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
}

type Saree struct {
	ID          int32         `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Price       string        `json:"price"`
	Stock       sql.NullInt32 `json:"stock"`
	ImageUrl    string        `json:"image_url"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

type User struct {
	ID             int64          `json:"id"`
	Username       string         `json:"username"`
	HashedPassword string         `json:"hashed_password"`
	Email          string         `json:"email"`
	FullName       string         `json:"full_name"`
	Role           sql.NullString `json:"role"`
	IsAdmin        bool           `json:"is_admin"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}
